### PR TITLE
Google Common, Google Cloud Pub/Sub gRPC: Add google-application-default credentials and StreamingPull auto-reconnect

### LINKED ISSUE #1458: pekko-connectors-google-cloud-pub-sub-grpc: StreamingPull does not reconnect on server-side disconnect
`GooglePubSub.subscribe` (Streaming Pull) silently stops receiving messages when the gRPC server closes the connection. Unlike the official Google Cloud Pub/Sub client libraries, pekko-connectors does not implement automatic reconnection.

## Environment

- pekko-connectors-google-cloud-pub-sub-grpc: **1.2.0**
- pekko-stream: **1.4.0**
- JVM: 21
- Runtime: Google Cloud Run

## Problem

Google Pub/Sub servers periodically close StreamingPull connections for expected reasons (idle timeout, server-side rebalancing, etc.). When this happens, the gRPC stream fails with:

```
io.grpc.StatusRuntimeException: UNAVAILABLE: The StreamingPull stream closed
for an expected reason and should be recreated, which is done automatically
if using Cloud Pub/Sub client libraries.
```

The error message states reconnection is automatic "if using Cloud Pub/Sub client libraries" — however, pekko-connectors is **not** a Google client library. It uses low-level gRPC stubs directly and does **not** implement reconnection logic.

When the gRPC stream is closed:

1. `PekkoNettyGrpcClientGraphStage` receives `onCallClosed` with `UNAVAILABLE` status
2. The Pekko Source emits `onError` (stream failure)
3. `Supervision.Resume` does **not** help — it only handles errors in downstream processing stages, not source failure
4. The entire Pekko Stream terminates silently
5. No more messages are received until the application is restarted

This is particularly problematic on Cloud Run where the instance stays alive (healthcheck passes) but the subscriber is dead.

## Steps to Reproduce

1. Create a Streaming Pull subscriber using `GooglePubSub.subscribe`:

```scala
GooglePubSub
  .subscribe(request, pollInterval = 1.second)
  .mapAsync(parallelism)(processMessage)
  .to(GooglePubSub.acknowledge(parallelism = 1))
  .run()
```

2. Wait for the server to close the connection (typically after idle period)
3. Observe that no new messages are received
4. The application continues running (healthcheck passes) but the stream is dead

## Misleading Error Message

The gRPC error message says:

> "...which is done automatically if using Cloud Pub/Sub client libraries"

This is misleading in the context of pekko-connectors because:

- Users may assume pekko-connectors qualifies as a "client library" that handles reconnection
- The official Google `google-cloud-pubsub` Java library (`com.google.cloud:google-cloud-pubsub`) **does** reconnect automatically
- pekko-connectors uses raw gRPC stubs (`com.google.pubsub.v1`) without reconnection logic

## Current Workaround

Wrap `GooglePubSub.subscribe` with `RestartSource.withBackoff`:

```scala
val restartSettings = RestartSettings(
  minBackoff = 3.seconds,
  maxBackoff = 30.seconds,
  randomFactor = 0.2
)

RestartSource
  .withBackoff(restartSettings) { () =>
    GooglePubSub.subscribe(request, pollInterval = 1.second)
  }
  .via(killSwitch.flow)  // SharedKillSwitch for graceful shutdown
  .mapAsync(parallelism)(processMessage)
  .to(GooglePubSub.acknowledge(parallelism = 1))
  .run()
```

Note: `UniqueKillSwitch` via `KillSwitches.single` cannot be used with `RestartSource` because `RestartSource` materializes to `NotUsed`. Use `SharedKillSwitch` via `KillSwitches.shared(name)` instead.

## Suggested Fix

One or more of the following:

1. **Document the reconnection requirement** — Add a prominent note in the `GooglePubSub.subscribe` scaladoc and user guide that `RestartSource` is required for production use
2. **Built-in reconnection** — Implement reconnection logic inside `GooglePubSub.subscribe`, similar to the official Google client libraries
3. **Provide a convenience method** — e.g. `GooglePubSub.subscribeWithRestart(request, restartSettings)` that wraps the source with `RestartSource` out of the box

## Stack Trace

```
io.grpc.StatusRuntimeException: UNAVAILABLE: The StreamingPull stream closed for an expected reason and should be recreated
    at io.grpc.Status.asRuntimeException(Status.java:532)
    at o.a.pekko.grpc.internal.PekkoNettyGrpcClientGraphStage$anon$1.onCallClosed(PekkoNettyGrpcClientGraphStage.scala:178)
    at o.a.pekko.grpc.internal.PekkoNettyGrpcClientGraphStage$anon$1.$anonfun$callback$1(PekkoNettyGrpcClientGraphStage.scala:81)
    at o.a.pekko.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:484)
    ...
```

### LINKED ISSUE #1493: pekko-connectors-google-common: custom credential resolution should be replaced with google-auth-library-java
## Problem
pekko-connectors-google-common reimplements Google's credential resolution instead of delegating to google-auth-library-java. This is a design issue that leads to:

1. Incomplete GCP environment support

The custom implementation does not correctly handle GKE Workload Identity, while `GoogleCredentials.getApplicationDefault()` works on the same Pod. Reimplementing authentication means that every change or addition to a GCP environment requires `pekko-connectors` to catch up.

2. No non-deprecated escape hatch

The only way to bypass the custom implementation (`withCallCredentials`) is **deprecated** and has no replacement.

**google-auth-library-java is maintained by Google, uses standard HTTP clients (no Pekko HTTP dependency), and supports all GCP environments. There is no benefit to reimplementing this.**

## Proposal
Replace the custom credential resolution with `GoogleCredentials.getApplicationDefault()` from google-auth-library-java.

### PR DESCRIPTION
**Pull request by hanishi**
This PR addresses two related issues affecting the production use of `pekko-connectors` with 
Google Cloud Pub/Sub:

**Problem 1: Credential resolution doesn't support all GCP environments** (#1493)

`pekko-connectors` implements its own credential resolution chain (the application-default provider tries service-account, compute-engine, user-access, and access-token in sequence). 
This custom implementation must maintain parity with every GCP environment Google adds; for example, GKE Workload Identity requires specific token exchange logic that `GoogleCredentials.getApplicationDefault()` already handles. Rather than maintaining a parallel implementation, the connector should delegate to Google's maintained library.

To use the new Google-native credential resolution:  
```
  pekko.connectors.google.credentials {                                                                                                                                                                     
    provider = google-application-default                                                                                                                                                                   
    google-application-default {
    project-id = "my-project"                                                                                                                                                                             
      # or via env: project-id = ${?GOOGLE_CLOUD_PROJECT}   
    }                                                                                                                                                                                                       
  }
```

The existing provider = application-default (the legacy custom chain) continues to work unchanged. 

**Problem 2: StreamingPull silently stops receiving messages** (#1458)

Google's Pub/Sub servers periodically close `StreamingPull` connections (idle timeout, rebalancing, infrastructure changes). When this happens, the gRPC stream emits UNAVAILABLE and terminates. Unlike Google's official client libraries, which reconnect automatically, `pekko-connectors`'s _subscribe()_ simply dies; the application appears healthy (healthchecks pass), but the subscriber is dead until a full restart.

**Problem 3: Redundant eager credential resolution** (discovered during this work)

PubSubSettings eagerly called `GoogleCredentials.getApplicationDefault()` during construction, then `PekkoGrpcSettings` discarded those credentials and re-resolved them through `GoogleSettings`. This was wasteful and could fail at startup in environments where users configured a different credential provider.

 Auth flow cleanup                                                                                                                                                                                         
                                                                                                                                                                                                            
  - PubSubSettings no longer eagerly resolves credentials. It's now purely connection config (host/port/TLS)                                                                                               
  - PekkoGrpcSettings always resolves credentials from GoogleSettings. No more branching on deprecated vs non-deprecated path                                                                              
  - DeprecatedCredentials wrapper class deleted. No longer needed                                                                                                                                          
                                                                                                                                                                                                            
  Auth flow:
  
 **Current**
 ```mermaid                                                                                                                                                                                                       
  sequenceDiagram                                                                                                                                                                                           
      participant App as Application                                                                                                                                                                        
      participant PS as PubSubSettings                                                                                                                                                                      
      participant PGS as PekkoGrpcSettings                                                                                                                                                                  
      participant GS as GoogleSettings                                                                                                                                                                      
      participant Creds as Credentials    
      participant GAuth as google-auth-library<br/>(GoogleCredentials)                                                                                                                                      
      participant gRPC as gRPC Channel                                                                                                                                                                      
                                          
      Note over App,gRPC: Initialization Phase                                                                                                                                                              
                                                                                                                                                                                                            
      App->>PS: PubSubSettings(system)
      PS->>PS: read callCredentials = "deprecated"                                                                                                                                                          
      PS->>GAuth: GoogleCredentials.getApplicationDefault() 
      GAuth-->>PS: GoogleCredentials (eagerly resolved)                                                                                                                                                     
      PS->>PS: wrap in DeprecatedCredentials(MoreCallCredentials.from(...))
                                                                                                                                                                                                            
      App->>GS: GoogleSettings(system)                                                                                                                                                                      
      GS->>Creds: Credentials(config)                                                                                                                                                                       
      alt provider = "application-default"                                                                                                                                                                  
          Creds->>Creds: try service-account → compute-engine → user-access → access-token
      end                                                                                                                                                                                                   
                                                            
      Note over App,gRPC: gRPC Client Creation                                                                                                                                                              
                                                                                                                                                                                                            
      App->>PGS: fromPubSubSettings(pubSubSettings, googleSettings)                                                                                                                                         
      PGS->>PGS: build GrpcClientSettings (host, port, TLS)                                                                                                                                                 
      PGS->>PGS: detect DeprecatedCredentials               
      Note over PGS: Discards eagerly-loaded credentials                                                                                                                                                    
      PGS->>PGS: log deprecation warning      
      PGS->>GS: googleSettings.credentials.asGoogle()                                                                                                                                                       
      GS-->>PGS: com.google.auth.Credentials                                                                                                                                                                
      PGS->>PGS: MoreCallCredentials.from(credentials)                                                                                                                                                      
      PGS->>gRPC: GrpcClientSettings.withCallCredentials(...)                                                                                                                                               
                                                                                                                                                                                                            
      Note over App,gRPC: Per-Request Phase                                                                                                                                                                 
                                                                                                                                                                                                            
      App->>gRPC: publish() / streamingPull()                                                                                                                                                               
      gRPC->>GAuth: credentials.getRequestMetadata()                                                                                                                                                        
      GAuth->>GAuth: refresh token if expired               
      GAuth-->>gRPC: {"Authorization": ["Bearer <token>"]}
 ```
 
  **After**
  ```mermaid
 sequenceDiagram                                                                                                                                                                                           
      participant App as Application                                                                                                                                                                      
      participant PS as PubSubSettings
      participant PGS as PekkoGrpcSettings                                                                                                                                                                  
      participant GS as GoogleSettings                                                                                                                                                                      
      participant Creds as Credentials                                                                                                                                                                      
      participant GAD as GoogleApplicationDefaultCredentials                                                                                                                                                
      participant GAuth as google-auth-library<br/>(GoogleCredentials)                                                                                                                                      
      participant gRPC as gRPC Channel                                                                                                                                                                      
                                                                                                                                                                                                            
      Note over App,gRPC: Initialization Phase                                                                                                                                                              
                                                                                                                                                                                                          
      App->>PS: PubSubSettings(system)                                                                                                                                                                      
      PS->>PS: read host, port, TLS config                                                                                                                                                                
      PS->>PS: read callCredentials config string                                                                                                                                                           
      Note over PS: No eager credential resolution                                                                                                                                                          
                                                                                                                                                                                                            
      App->>GS: GoogleSettings(system)                                                                                                                                                                      
      GS->>Creds: Credentials(config)                                                                                                                                                                       
      alt provider = "google-application-default"                                                                                                                                                           
          Creds->>GAD: GoogleApplicationDefaultCredentials(projectId, scopes)                                                                                                                               
          GAD->>GAuth: GoogleCredentials.getApplicationDefault()                                                                                                                                            
          Note over GAD,GAuth: Single call — single source of truth                                                                                                                                         
          GAuth-->>GAD: GoogleCredentials                                                                                                                                                                   
      else provider = "application-default" (legacy)                                                                                                                                                        
          Creds->>Creds: try service-account → compute-engine → user-access → access-token                                                                                                                  
      else provider = "service-account" / "compute-engine" / etc.                                                                                                                                           
          Creds->>Creds: parse specific provider                                                                                                                                                            
      end                                                                                                                                                                                                   
                                                                                                                                                                                                          
      Note over App,gRPC: gRPC Client Creation                                                                                                                                                              
                                                                                                                                                                                                          
      App->>PGS: fromPubSubSettings(pubSubSettings, googleSettings)                                                                                                                                         
      PGS->>PGS: build GrpcClientSettings (host, port, TLS)                                                                                                                                               
                                                                                                                                                                                                            
      alt callCredentials = "none" (explicit opt-out)                                                                                                                                                       
          Note over PGS: No credentials attached (e.g. emulator)                                                                                                                                            
      else default                                                                                                                                                                                          
          PGS->>GS: googleSettings.credentials.asGoogle()                                                                                                                                                 
          GS-->>PGS: com.google.auth.Credentials                                                                                                                                                            
          PGS->>PGS: MoreCallCredentials.from(credentials)                                                                                                                                                  
      end                                                                                                                                                                                                   
                                                                                                                                                                                                            
      PGS->>gRPC: GrpcClientSettings.withCallCredentials(...)                                                                                                                                               
                                                                                                                                                                                                            
      Note over App,gRPC: Per-Request Phase                                                                                                                                                                 
                                                                                                                                                                                                          
      App->>gRPC: publish() / streamingPull()                                                                                                                                                               
      gRPC->>GAuth: credentials.getRequestMetadata()                                                                                                                                                      
      GAuth->>GAuth: refresh token if expired                                                                                                                                                               
      GAuth-->>gRPC: {"Authorization": ["Bearer <token>"]}                                                                                                                                                 
```

Fixes #1493

Fixes #1458

### CODE REVIEW

File: google-cloud-pub-sub-grpc/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/pubsub/grpc/impl/PekkoGrpcSettings.scala [hunk 1]
```diff
@@ -43,13 +43,10 @@ import scala.annotation.nowarn
         .withFallback(sys.settings.config.getConfig("pekko.grpc.client.\"*\"")))
 
     (config.callCredentials: @nowarn("msg=deprecated")) match {
-      case None                           => settings
-      case Some(DeprecatedCredentials(_)) => // Deprecated credentials were loaded from config so override them
-        sys.log.warning(
-          "Config path pekko.connectors.google.cloud.pubsub.grpc.callCredentials is deprecated, use pekko.connectors.google.credentials")
+      case Some(creds) => settings.withCallCredentials(creds)
+      case None        =>
```
[the remark this answers is not in the document]
Comment (pjfanning) [reply google-cloud-pub-sub-grpc/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/pubsub/grpc/impl/PekkoGrpcSettings.scala]: I guess since this is targeted at 2.0.0 that we can risk breaking the usage for users who for some unknown reason might need no credentials

File: google-cloud-pub-sub-grpc/k8s/GkeAuthTest.scala [hunk 2]
```diff
@@ -0,0 +1,79 @@
+/*
```
Comment (pjfanning) [inline google-cloud-pub-sub-grpc/k8s/GkeAuthTest.scala]: use an org.apache.pekko prefix to the package name

use the standard Apache license header unless you took this code from Akka

can you explain this code generally? - it doesn't look like a test

File: google-cloud-pub-sub-grpc/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/pubsub/grpc/FlowControl.scala [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+object FlowControl {
+
+  /** Create a new [[FlowControl]] instance. */
+  def apply(maxOutstandingMessages: Long): FlowControl =
+    new FlowControl(maxOutstandingMessages)
+
+  /** Java API: Create a new [[FlowControl]] instance. */
+  def create(maxOutstandingMessages: Long): FlowControl =
+    new FlowControl(maxOutstandingMessages)
+}
```
Comment (pjfanning) [inline google-cloud-pub-sub-grpc/src/main/scala/org/apache/pekko/stream/connectors/googlecloud/pubsub/grpc/FlowControl.scala]: No file should end with this symbol. The Red Circle with a line through it. Can you add an EOL at the end of all text files?

**Comment by hanishi** [comment]
@pjfanning 
OK. I'll stop force-pushing and keep commits as individual changes from now on.

**Review by pjfanning — APPROVED** [review]
lgtm - I think we can merge this as is

I would like to get some follow up done but the PR is big enough already.

For one, I think we should extend the Java DSL because the changes in this PR seem to only seem to add the new APIs to the Scala DSL.
